### ISSUE TITLE
Help me: ImportError: No module named 'pyzk'

### ISSUE THREAD

**Issue by biencuong** [adrobinoga/pyzatt#1]
root@OrangePI:/home/zk/pyzatt/tests# python3 test_terminal.py
Traceback (most recent call last):
  File "test_terminal.py", line 5, in <module>
    import pyzk.pyzk as pyzk
ImportError: No module named 'pyzk'
Help me!

**Comment by adrobinoga** [comment]
Hi, that happens because python can't find de module, to do so you may execute
`export PYTHONPATH="${PYTHONPATH}:/home/zk/pyzatt//lib"`
Then
`python3 test_terminal.py`

That will work only in the current terminal, to make it permanent you can append the export command to the .bashrc file

**Comment by biencuong** [comment]
I did as you instructed, but still encountered the error as above.
`root@OrangePI:/home/zk/pyzatt/tests# python3 test_realtime.py
Traceback (most recent call last):
  File "test_realtime.py", line 7, in <module>
    import pyzk.pyzk as pyzk
ImportError: No module named 'pyzk'
`
Can you write the sutup.py file as a pyzk library?

**Comment by adrobinoga** [comment]
done, pull new changes and run
`python3 setup.py install --user`

**Comment by biencuong** [comment]
Great. Thank you!

**Comment by adrobinoga** [comment]
Glad I could help. Thanks for noting the issue!

**Comment by biencuong** [comment]
Thanks for the fast support!
I have a problem with the following error:
root@OrangePI:/home/zk/pyzatt/tests# python3 test_realtime.py

################################################################################
#       TEST OF REALTIME FUNCTIONS


################################################################################
#       1.Realtime Test

Traceback (most recent call last):
  File "test_realtime.py", line 36, in <module>
    z.read_all_user_id()
  File "/root/.local/lib/python3.4/site-packages/PyZatt-1.0-py3.4.egg/pyzk/zkmodules/data_user.py", line 49, in read_all_user_id
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
Best regards!

**Comment by rakcomputing** [comment]
my error : import time
from zk import ZK

def add_time_log(ip_address, port, user_id, timestamp):
    zk_instance = ZK(ip_address, port=port)
    try:
        # Connect to the device
        conn = zk_instance.connect()
        if conn:
            print("Connection successful")
            # Prepare attendance data
            attendance_data = f"{user_id}\t{timestamp}\n"
            # Push attendance data to the device
            conn.push_attendance_data(attendance_data)
            print("Time log added successfully")
        else:
            print("Failed to connect")
    except Exception as e:
        print("Error:", e)
    finally:
        # Disconnect from the device
        zk_instance.disconnect()

if __name__ == "__main__":
    # Example usage
    device_ip = '192.168.1.202'  # Replace with your device IP
    port = 4370  # Replace with the port of your device
    user_id = '38'  # Example user ID
    timestamp = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())  # Current timestamp
    add_time_log(device_ip, port, user_id, timestamp)
------------------
help to fix  error : Connection successful
Error: 'ZK' object has no attribute 'push_attendance_data'
