### ISSUE TITLE
Unable to install this library

### ISSUE THREAD

**Issue by slintak** [adrobinoga/pyzatt#17]
I am unable to install this library because of invalid syntax in `setup.py`:

```
version='version='2.0.0'',
                            ^
    SyntaxError: invalid syntax
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

https://github.com/adrobinoga/pyzatt/blob/6e81779e458d28650d39e9837781aeaff9bda2fd/setup.py#L51

The problematic line was added in commit 6e81779e458d28650d39e9837781aeaff9bda2fd.

**Comment by adrobinoga** [comment]
Thanks!
I had a typo when bumping the version
