### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by biencuong** [adrobinoga/pyzatt#2]
Please help me with this error:
root@OrangePI:/home/zk/pyzatt/tests# python3 test_realtime.py
##############################################################################
#       TEST OF REALTIME FUNCTIONS
##############################################################################
#       1.Realtime Test
Traceback (most recent call last):
  File "test_realtime.py", line 36, in <module>
    z.read_all_user_id()
  File "/root/.local/lib/python3.4/site-packages/PyZatt-1.0-py3.4.egg/pyzk/zkmodules/data_user.py", line 49, in read_all_user_id
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

Best regards!

**Comment by biencuong** [comment]
> Hi biencuong,
> Two questions:
> 
> 1. What device do you have (model) ?
> 2. There are valid users stored in the terminal ?

1. TC 100, Firmware Version: : Ver 6.60 Aug 10 2015
2. There are valid users in the machine.
--------------
With the pyzk library, I process by command:
import sys
sys.path.append("zk")
reload(sys)

**Comment by adrobinoga** [comment]
Could you please explain what is the idea behind
```
import sys
sys.path.append("zk")
reload(sys)
```
I didn't understand

**Comment by biencuong** [comment]
> Bạn có thể giải thích ý tưởng đằng sau
> 
> ```
> import sys
> sys.path.append("zk")
> reload(sys)
> ```
> Tôi không hiểu
import sys 
sys.path.append ("zk") 
reload (sys) 
sys.setdefaultencoding ('utf8')
Since the username has a unicode character, I use that to fix the error "UnicodeDecodeError: 'ascii' codec"

**Comment by adrobinoga** [comment]
So you fixed the error with that? If so it is working fine or there is still a problem? with the realtime test it should appear some events on the terminal, that can be triggered by placing finger on the reader, for example

**Comment by biencuong** [comment]
> Vì vậy, bạn sửa lỗi với điều đó? Nếu vậy nó hoạt động tốt hay vẫn còn một vấn đề? với kiểm tra thời gian thực nó sẽ xuất hiện một số sự kiện trên thiết bị đầu cuối, có thể được kích hoạt bằng cách đặt ngón tay trên đầu đọc, ví dụ

**Comment by biencuong** [comment]
> So you fixed the error with that? If so it is working fine or there is still a problem? with the realtime test it should appear some events on the terminal, that can be triggered by placing finger on the reader, for example

With the fanzimi's pyzk library, it was solved, and your pyzatt library was not resolved, it was not running.
root@OrangePI:/home/zk/pyzatt/tests# python3 test_realtime.py
Traceback (most recent call last):
  File "test_realtime.py", line 4, in <module>
    reload(sys)
NameError: name 'reload' is not defined

**Comment by adrobinoga** [comment]
Im not sure, but maybe replacing 49 line in data_user.py with

```
# extract user name
user_name = users_dataset[i+11:i+35].decode('utf-8')
```

Should work, I did this in a new branch ` issue2-name_error`

**Comment by biencuong** [comment]
I did it, thank you!
